version: '3.7'
services:

  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    environment: 
      APP_ENV: "test"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: admin
      MONGODB_USERNAME: mongoadmin
      MONGODB_PASSWORD: topsecret
      MONGODB_HOSTNAME: mongodb
    ports:
      - "80:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: topsecret
      MONGO_INITDB_DATABASE: admin
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
